In [1]:
import numpy as np

In [8]:
def valid_state(s):
    if(s[0]>=0 and s[0]<4):
        if(s[1]>=0 and s[1]<4):
            return(True)
    return(False)
def terminal(s):
    if(s[0]==0 and s[1]==0):
        return(True)
    if(s[0]==3 and s[1]==3):
        return(True)
    return(False)
def policy_evaluation(gridworld=None,policy=None):
    gamma = 1
    if(gridworld is None):
        gridworld = np.zeros((4,4))
    mx = [-1,0,0,1]
    my = [0,1,-1,0]
    if(policy is None):
        policy = np.ones((4,4,4))*0.25
    changes = True
    count = 0
    while(changes):
        count+=1
        changes= False
        for i in range(4):
            for j in range(4):
                total = 0
                state = (i,j)
                if(terminal(state)):
                        continue
                for d in range(4):
                    dx = mx[d]
                    dy = my[d]
                    dest = (dx,dy) 
                    new_s = np.add(state,dest) 
                    if(not valid_state(new_s)):
                        new_s=state
                    r=-1
#                     if(terminal(new_s)):
#                         r=0
                    r += gamma*gridworld[new_s[0],new_s[1]]
                    total+=policy[i,j,d]*r
                if(np.abs(total-gridworld[i,j])>0.01):
                    changes = True
                gridworld[i,j]=total
        if(count%10==0):
            display(gridworld)
            print("evalutation count",count)
    return(gridworld)

In [9]:
grid = policy_evaluation()

array([[  0.        ,  -7.82506756, -11.12181872, -12.22765503],
       [ -7.82506756, -10.42037166, -11.76933739, -11.86339862],
       [-11.12181872, -11.76933739, -11.0538181 ,  -8.81387889],
       [-12.22765503, -11.86339862,  -8.81387889,   0.        ]])

evalutation count 10


array([[  0.        , -11.42591538, -16.29940807, -17.92681232],
       [-11.42591538, -14.84125831, -16.57033147, -16.60954761],
       [-16.29940807, -16.57033147, -15.10598674, -11.83929409],
       [-17.92681232, -16.60954761, -11.83929409,   0.        ]])

evalutation count 20


array([[  0.        , -12.92728455, -18.457828  , -20.30255383],
       [-12.92728455, -16.68363739, -18.57073269, -18.5870755 ],
       [-18.457828  , -18.57073269, -16.79396009, -13.09955577],
       [-20.30255383, -18.5870755 , -13.09955577,   0.        ]])

evalutation count 30


array([[  0.        , -13.55296045, -19.35732082, -21.29261243],
       [-13.55296045, -17.45142381, -19.40437232, -19.41118296],
       [-19.35732082, -19.40437232, -17.49739929, -13.62475213],
       [-21.29261243, -19.41118296, -13.62475213,   0.        ]])

evalutation count 40


array([[  0.        , -13.81370235, -19.73217221, -21.70520586],
       [-13.81370235, -17.77138835, -19.75178028, -19.75461852],
       [-19.73217221, -19.75178028, -17.790548  , -13.84362056],
       [-21.70520586, -19.75461852, -13.84362056,   0.        ]])

evalutation count 50


array([[  0.        , -13.92236299, -19.88838642, -21.87714856],
       [-13.92236299, -17.90472921, -19.89655781, -19.89774061],
       [-19.88838642, -19.89655781, -17.91271373, -13.934831  ],
       [-21.87714856, -19.89774061, -13.934831  ,   0.        ]])

evalutation count 60


In [24]:
def print_policy(policy):
    mx = [-1,0,0,1]
    my = [0,1,-1,0]
    
    z = np.zeros((4,4))
    for i in range(4):
        for j in range(4):
            val = np.argmax(policy[i,j,:])
    #         print(val)
#             z[i,j]=val
            print("({0},{1})".format(mx[val],my[val]),end=" ")
        print()
#     plt.contour(z)
#     plt.show()
#     print(z)
def policy_improvement(gridworld):
    stable = False
    policy = []
    mx = [-1,0,0,1]
    my = [0,1,-1,0]
    policy = np.ones((4,4,4))*0.25
#     policy[:,:,0]=
    while(not stable):
        stable=True
        for i in range(4):
            for j in range(4):
                state = (i,j)
                if(terminal(state)):
                    continue
                old_action = np.argmax(policy[i,j,:])
                old_actions = np.where(policy[i,j,:]==policy[i,j,:].max())[0]
                print(old_actions,i,j)
                best_value = -np.inf
                best_move = None
                for d in range(4):
                    dest = (mx[d],my[d])
                    new_s = np.add(state,dest)
                    if(not valid_state(new_s)):
                        new_s =  state
                    if(terminal(new_s)):
                        r = policy[i,j,d]*(gridworld[new_s[0],new_s[1]])
                    else:
                        r = policy[i,j,d]*(-1+gridworld[new_s[0],new_s[1]])
                    if(r>best_value):
#                         print(best_value,r,d)
                        best_value = r
                        best_move = d
                policy[i,j,:]=0
                policy[i,j,best_move]=1
#                 stable = True
                if(best_move not in old_actions):
                    stable=False
                    print(best_move,old_action)
                
                        
        if(not stable):
            print("not stable")
            display(gridworld)
            gridworld=policy_evaluation(gridworld,policy)
            display(gridworld)
            print_policy(policy)
    return(policy)
                
                

In [25]:
p = policy_improvement(grid)

[0 1 2 3] 0 1
[0 1 2 3] 0 2
[0 1 2 3] 0 3
[0 1 2 3] 1 0
[0 1 2 3] 1 1
[0 1 2 3] 1 2
[0 1 2 3] 1 3
[0 1 2 3] 2 0
[0 1 2 3] 2 1
[0 1 2 3] 2 2
[0 1 2 3] 2 3
[0 1 2 3] 3 0
[0 1 2 3] 3 1
[0 1 2 3] 3 2


In [26]:
p

array([[[0.25, 0.25, 0.25, 0.25],
        [0.  , 0.  , 1.  , 0.  ],
        [0.  , 0.  , 1.  , 0.  ],
        [0.  , 0.  , 1.  , 0.  ]],

       [[1.  , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 1.  , 0.  ],
        [1.  , 0.  , 0.  , 0.  ],
        [1.  , 0.  , 0.  , 0.  ]],

       [[1.  , 0.  , 0.  , 0.  ],
        [1.  , 0.  , 0.  , 0.  ],
        [1.  , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , 1.  ]],

       [[1.  , 0.  , 0.  , 0.  ],
        [1.  , 0.  , 0.  , 0.  ],
        [0.  , 1.  , 0.  , 0.  ],
        [0.25, 0.25, 0.25, 0.25]]])